CREATE TABLE IF NOT EXISTS USER (
  USER_ID INTEGER PRIMARY KEY NOT NULL,
  LOGIN CHAR(20) NOT NULL UNIQUE,
  PASSWORD CHAR(20) NOT NULL,
  FIRST_NAME CHAR(32),
  LAST_NAME CHAR(32),
  MIDDLE_NAME CHAR(32),
  CREATE_TS DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO USER (LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES ('LasGIS', '123', 'Ласкин', 'Владимир', 'Вадимович');
