app:
  name: hiber-check

spring:
#  flyway:
#    locations: classpath:/db
#    baselineOnMigrate: true
#    schemas: hiber
  jpa:
    properties:
      hibernate:
        default_schema: hiber
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
        current_session_context_class: thread
        connection:
#          driver_class: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/postgres
#          username: postgres
#          password: postgres
#          pool_size: 8
          autocommit: false
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

  #database connection
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari.schema: hiber

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE