server:
  port: 8099

spring:
  # r2dbc connection
  # see https://github.com/pgjdbc/r2dbc-postgresql
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/generic
    username: generic
    password: generic
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30

  data.r2dbc.repositories.enabled: true

settings:
  name: UI reactive
  version: @project.version@

# SpringDoc
springdoc:
  model-converters:
    polymorphic-converter:
      enabled: true
    deprecating-converter:
      enabled: true
#  show-actuator: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
#    path: /you-path/swagger-ui.html

#springdoc:
#    swagger-ui:
##        oauth:
##            realm: ${keycloak.realm}
##            app-name: ${spring.security.oauth2.client.registration.keycloak.clientName}
##        oauth2-redirect-url: ${spring.security.oauth2.client.registration.keycloak.redirect-uri}

#debug: true TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
