spring:
    # r2dbc connection
    # see https://github.com/pgjdbc/r2dbc-postgresql
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        properties:
            schema: prototype
        pool:
            enabled: true
            initial-size: 10
            max-idle-time: 1m
            max-size: 30

    data.r2dbc.repositories.enabled: true
