### GET user ID=1
GET http://localhost:8080/api/v2/user/1

### GET All users
GET http://localhost:8080/api/v2/user

### create first User
POST http://localhost:8080/api/v2/user
Content-Type: application/json

{
  "login": "first",
  "name": "User1",
  "password": "123",
  "roles": ["CHIEF", "OPERATOR"],
  "archived": false
}

### update first User to User2
PUT http://localhost:8080/api/v2/user/3
Content-Type: application/json

{
  "login": "Second",
  "name": "User2",
  "password": "1234",
  "roles": ["ADMIN", "SUPERVISOR"],
  "archived": false
}

### GET login = Second
GET http://localhost:8080/api/v2/user/login?login=Second

###
GET http://localhost:8080/api/v2/user/roles
