# название приложения
app.name: hiber-check
# локальнй порт
server.port: 8098

#  flyway:
#    locations: classpath:/db
#    baselineOnMigrate: true
#    schemas: hiber
spring:
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: update

#database connection
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    hikari.schema: hiber
