server:
  port: 8099

spring:

  # flyway migration
  flyway:
    locations:  classpath:/db/migration,classpath:/dev/db/migration
    baselineOnMigrate: true

  # database connection
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/git_admin
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
#      schema: prototype

local:
  server:
    port: 8099
