server:
  port: 8099

spring:

  # flyway migration
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baselineOnMigrate: true
    schemas: prototype

  # database connection
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      schema: prototype

local:
  server:
    port: 8099
